# This workflow will run all tests for every PR and subsequent merge to main.
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
#
# Copyright (c) 2022 AlertAvert.com.  All rights reserved.
# Author: Marco Massenzio (marco@alertavert.com)

name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Setup fake Credentials for Tests
      run: |
        cp gradle.properties.fake gradle.properties
        mkdir -p ~/.aws
        cat <<EOF > ~/.aws/credentials
        [default]
        aws_access_key_id = fake
        aws_secret_access_key = fake
        EOF
    - name: Build & Test
      run: |
        echo "keys: $(ls -l testdata)"
        chmod +x gradlew && ./gradlew test
